Rails.application.configure do

  ELASTIC_URL = ENV['ELASTIC_URL'] || puts('WARNING ====> No ELASTIC_URL given')
  ELASTIC_TIMEOUT = ENV['ELASTIC_TIMEOUT'] || puts('WARNING ====> No ELASTIC_TIMEOUT given')
  BASE_URL = ENV['BASE_URL'] || puts('WARNING ====> No BASE_URL given')
  REDIS_CACHE_URL = ENV['REDIS_CACHE_URL'] || puts('WARNING ====> No REDIS_CACHE_URL given')
  CACHE_TTL_IN_HOURS = ENV['CACHE_TTL_IN_HOURS'] || puts('WARNING ====> No CACHE_TTL_IN_HOURS given')
  REDIS_SESSION_URL = ENV['REDIS_SESSION_URL'] || puts('WARNING ====> No REDIS_SESSION_URL given')
  SESSION_LIFETIME_IN_HOURS = ENV['SESSION_LIFETIME_IN_HOURS'] || puts('WARNING ====> No SESSION_LIFETIME_IN_HOURS given')
  DATABASE_URL = ENV['DATABASE_URL'] || puts('WARNING ====> No DATABASE_URL given')
  RAILS_MAX_THREADS = ENV['RAILS_MAX_THREADS'] || puts('WARNING ====> No RAILS_MAX_THREADS given')
  PORT = ENV['PORT'] || puts('WARNING ====> No PORT given')
  WEB_CONCURRENCY = ENV['WEB_CONCURRENCY'] || puts('WARNING ====> No WEB_CONCURRENCY given')

end